package Controller;

import java.io.IOException;

import Model.ImportVehicle;
import application.Main;
import javafx.fxml.FXML;

import javafx.scene.control.TextField;
import javafx.scene.control.Label;
import javafx.scene.control.MenuBar;
import javafx.scene.control.TextArea;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class ImportVehiclesController {
	Main m = new Main();
	@FXML
	MenuBar menuBar;
	@FXML
	private Label label1;
	@FXML
	private TextField textbox1;
	@FXML
	private TextField textbox2;
	@FXML
	private TextField textbox3;
	@FXML
	private TextField textbox4;
	@FXML
	private TextField textbox5;
	@FXML
	private TextField textbox6;
	@FXML
	private TextField textbox7;
	@FXML
	private TextField textbox8;
	@FXML
	private TextArea textbox9;

	// Event Listener on Button.onMouseClicked
	@FXML
	public void Submit1(MouseEvent event) {
		// TODO Autogenerated
		System.out.println(textbox1.getText());//region no
		System.out.println(textbox2.getText());//company
		System.out.println(textbox3.getText());//model
		System.out.println(textbox4.getText());//type
		System.out.println(textbox5.getText());//price
		System.out.println(textbox6.getText());//year
		System.out.println(textbox7.getPromptText());//color
		System.out.println(textbox8.getText());//rent/day
		System.out.println(textbox9.getText());//description
		
		String regNo = textbox1.getText();
		String company = textbox2.getText();
		String model = textbox3.getText();
		String type = textbox4.getText();
		int price = Integer.parseInt(textbox5.getText());
		int year = Integer.parseInt(textbox6.getText());
		String color = textbox7.getText();
		int rentPerDay = Integer.parseInt(textbox8.getText());
		String desc = textbox9.getText();
		
		ImportVehicle importVehicle = new ImportVehicle();
		int result = importVehicle.importVehicle(regNo, company, model, type, price, year, color, rentPerDay, desc);
		
		if (result == 1) {
			label1.setText("RegNo Repeated");
		}
		
		if (result == 0) {
			label1.setText(" ");
			System.out.println("Successfully Imported!");
		}
		
		if (result == 2) {
			label1.setText("Error");
		}
	}
	
	public void goBack() throws IOException {
		Stage s = (Stage) menuBar.getScene().getWindow();
		m.changeScene(s, "../View/Dealer.fxml");
	}
}
