package Controller;

import java.io.IOException;

import Model.Signup;
import Model.UserInstance;
import application.Main;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.MenuBar;
import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class SignupController {
	@FXML
	Label label1;
	@FXML
	MenuBar menuBar;
	@FXML
	private TextField textbox1;
	@FXML
	private TextField textbox2;
	@FXML
	private TextField textbox3;
	@FXML
	private TextField textbox4;
	@FXML
	private TextField textbox5;
	@FXML
	private TextField textbox6;
	
	Main m = new Main();
	// Event Listener on Button.onMouseClicked
	@FXML
	public void Signup1(MouseEvent event) {
		// TODO Autogenerated
		String name = textbox1.getText();
		String address = textbox2.getText();
		String cnic = textbox3.getText();
		String contact = textbox4.getText();
		String email = textbox5.getText();
		String password = textbox6.getText();
		Signup signup = new Signup();
		
		boolean result = false;
		
		if (UserInstance.userType == "Customer") {
			result = signup.customerSignup(name, address, cnic, contact, email, password);
		}
		
		if (UserInstance.userType == "Dealer") {
			result = signup.dealerSignup(name, address, cnic, contact, email, password);
		}
		
		if (UserInstance.userType == "Admin") {
			result = signup.adminSignup(name, address, cnic, contact, email, password);
		}
		
		if (result == false) {
			label1.setText("Sign Up Failed!");
		} else {
			Stage s = (Stage) menuBar.getScene().getWindow();
			UserInstance.userType = "None";
			m.changeScene(s, "../View/Home.fxml");
		}
		
	}
	
	public void goBack(ActionEvent event) throws IOException {
		Stage s = (Stage) menuBar.getScene().getWindow();
		UserInstance.userType = "None";
		m.changeScene(s, "../View/Home.fxml");
	}
}

