package Controller;

import java.io.IOException;

import Model.Login;
import Model.UserInstance;
import application.Main;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.MenuBar;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class SigninController {
	@FXML
	MenuBar menuBar;
	@FXML
	TextField textbox1;
	@FXML
	TextField textbox2;
	@FXML
	Label label1;
	
	Main m = new Main();
	// Event Listener on Button.onMouseClicked
	@FXML
	public void signin1(MouseEvent event) {
		// TODO Autogenerated
		System.out.println(textbox1.getText());//textbox1
		System.out.println(textbox2.getText());//textbox2
		
		String email = textbox1.getText();
		String password = textbox2.getText();
		
		Login login = new Login();
		
		if (UserInstance.userType == "Customer") {
			boolean check = login.customerLogin(email, password);
			
			if (check == true) {
				label1.setText(" ");
				Stage s = (Stage) menuBar.getScene().getWindow();
				m.changeScene(s, "../View/CustomerHome.fxml");
			}else {
				label1.setText("Login Failed");
			}
		}
		
		if (UserInstance.userType == "Dealer") {
			boolean check = login.dealerLogin(email, password);
			
			if (check == true) {
				label1.setText(" ");
				Stage s = (Stage) menuBar.getScene().getWindow();
				m.changeScene(s, "../View/Dealer.fxml");
			}else {
				label1.setText("Login Failed");
			}
		}
		
		if (UserInstance.userType == "Admin") {
			boolean check = login.adminLogin(email, password);
			
			if (check == true) {
				label1.setText(" ");
				Stage s = (Stage) menuBar.getScene().getWindow();
				m.changeScene(s, "../View/Admin.fxml");
			}else {
				label1.setText("Login Failed");
			}
		}
	}
	
	public void goBack(ActionEvent event) throws IOException {
		Stage s = (Stage) menuBar.getScene().getWindow();
		UserInstance.userType = "None";
		m.changeScene(s, "../View/Home.fxml");
	}
}
